### ISSUE TITLE
kaminari pagination loaded too late

### ISSUE THREAD

**Issue by khoan** [collectiveidea/delayed_job_mongoid#10]
Delayed::Job.where.page(2) will spew undefined page method because delayed_job_mongoid got loaded then kaminari as can be seen via strategically placed puts statements in

```
../kaminari-0.12.3/lib/kaminari/railtie.rb
../delayed_job_mongoid-1.0.2/lib/delayed/backend/mongoid.rb
```

According to https://github.com/carlhuda/bundler/issues/107 kaminari will be required first then delayed_job_mongoid when Gemfile is as follow

``` ruby
gem 'rails', '~>3'
gem 'mongoid'
gem 'kaminari'
gem 'delayed_job'
gem 'delayed_job_mongoid'
```

quickest workaround is to mix in in initializer

``` ruby
Delayed::Job.send(:include, Kaminari::MongoidExtension::Document)
```

**Comment by martnst** [comment]
@khoan I fixed this by adding the following to the top of `initializers/rails_admin.rb`

    Delayed::Job.send(:include, RailsAdmin::Adapters::Mongoid::Extension)

**Comment by dblock** [comment]
This is old. Doing some bookkeeping and closing this.
