### ISSUE TITLE
Stack level too deep

### ISSUE THREAD

**Issue by luciancancescu** [collectiveidea/delayed_job_mongoid#21]
I have the following issue with a project using MongoDB, rails 3.1.3 and ruby 1.9.2:

When I use the Thin server, every time delay is called (such as: UserMailer.delay.password_reset(..) ) I get stack level too deep and the website crashes. However, when I start the WEBrick server, it works just fine and emails are sent. I followed the instructions to setup delayed_job for mongoid and rails 3.

Here is the output of the error: 

SystemStackError in PasswordResetsController#create

stack level too deep

Full Trace
actionpack (3.1.3) lib/action_dispatch/middleware/reloader.rb:73

Can you please give me some hints why Thin fails and WEBrick works? Is this a problem with delayed_job or with Thin? 

Thanks,
Lucian

**Comment by dblock** [comment]
Closing, see above.
