### ISSUE TITLE
Find job fails when :first and :condition is used

### ISSUE THREAD

**Issue by christianhager** [collectiveidea/delayed_job_mongoid#24]
Hi - I ran into a problem using cedar stack on heroku. The find method failed with Mongoid::Errors::DocumentNotFound: Document not found for class Delayed::Backend::Mongoid::Job with id(s) [:first, {:conditions=>{:_id=>"4f1d8ab08fc8ea000100000b"}}].

I'm using these gems:
rails (3.1.3)
delayed_job_mongoid (1.0.8)
delayed_job (~> 3.0.0)
mongoid (>= 2.0)

This change fixed the issue though I'm probably not seeing some important conflict this change may have
https://github.com/christianhager/delayed_job_mongoid/commit/42c984f097175e8da3f7281a3ae9c3d5893cab5e

**Comment by dblock** [comment]
This is old. Doing some bookkeeping. I believe this has long been fixed.
