### ISSUE TITLE
after upgraded to 3.2.1, getting warning about ActiveSupport::Concern

### ISSUE THREAD

**Issue by niksosf** [collectiveidea/delayed_job_mongoid#25]
The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in Delayed::Backend::Mongoid::Job instead. (called from require at /Users/nik/.rvm/gems/ruby-1.9.3-p0@global/gems/bundler-1.0.21/lib/bundler/runtime.rb:68)

Will this be addressed in an upcoming update or is it something I can do myself to correct?

Best,
Nik

**Comment by dblock** [comment]
This has long been addressed I believe, closing.
