### ISSUE TITLE
Support for Mongoid v2.4.0+

### ISSUE THREAD

**Issue by wchrisjohnson** [collectiveidea/delayed_job_mongoid#35]
I'm not clear on whether the master branch of this gem supports Mongoid 2.4.0+ explicitly. I'm currently evaluating it with 2.4.0, and it _seems_ to be working properly. However, I don't want to get bit down the road... Can someone confirm for me?

https://github.com/collectiveidea/delayed_job_mongoid/issues/32

What are the requirements for using the version on master?

**Comment by dblock** [comment]
This should be closed, at this point nobody should be using mongoid 2.x.

**Comment by dblock** [comment]
Closing.
