### ISSUE TITLE
Should the index spec be updated to match the current #reserve method?

### ISSUE THREAD

**Issue by contentfree** [collectiveidea/delayed_job_mongoid#39]
It was updated a few years ago, but it seems that it's drifted some. For example, the index doesn't contain any knowledge of failed_at.

**Comment by dblock** [comment]
This is old. Doing some bookkeeping. It seems to me that the answer is "yes" to this, care to take care of it @contentfree?

**Comment by johnnyshields** [comment]
This is done already
