### ISSUE TITLE
Redesign the findAndModify query and/or indexes to be more performant

### ISSUE THREAD

**Issue by contentfree** [collectiveidea/delayed_job_mongoid#44]
Right now I have roughly 200 workers and a job table of ~7000 jobs (not many jobs, but they're long-running).

The findAndModify as it is today, with the indexes prescribed plus another for queue, is  relatively slow and when you have many workers the write lock used by findAndModify brings Mongodb to its knees (which in turn makes everything glacially slower). Currently, it just uses a BasicCursor and scans the whole job table (at least if you use named queues).

The [answer to this StackOverflow question](http://stackoverflow.com/a/8490490/137641) is insightful though it doesn't contain any explicit suggestions.

Can this be rectified by adding or adjusting indexes?

**Comment by cheenu** [comment]
I see this issue with only 3 workers and 3000 queued jobs (that execute very, very fast - 100s of them execute in a second). Used @contentfree suggestion to move the collection to another database which has isolated the problem such that it doesn't affect other non-DJ operations but isn't a permanent solution.

+1 for rewriting the query to be more efficient.

**Comment by dimzon** [comment]
You are using $or clause - this is extreme ineffective in term of index usage. I believe You must change your data scheme (maybe some denormalization) to take away all $or and $in clauses.

**Comment by contentfree** [comment]
A better option would probably be to just move to a real work queue. We've been bringing in DJ-like features into Backburner (which is a beanstalkd client).

**Comment by scottmessinger** [comment]
I took some hints from https://github.com/rschmukler/agenda/issues/104 and added the following index: 

```js
{ locked_by: -1, priority: 1, run_at: 1 }
```

and my lock percentage went from 100%+ to normal levels

**Comment by fltiago** [comment]
@scottmessinger I looked at the mongoid code and already have the index that in point out: https://github.com/collectiveidea/delayed_job_mongoid/blob/master/lib/delayed/backend/mongoid.rb#L24

**Comment by dblock** [comment]
This is old. Doing some bookkeeping. Anyone cares to figure out what to do with this? Also is this related to #46?
