### ISSUE TITLE
Frozen Hash in Heroku

### ISSUE THREAD

**Issue by disheng** [collectiveidea/delayed_job_mongoid#45]
I'm getting a Frozen Hash error after the job is completed (the job is completed correctly). 

Here the exception: 

```
rake aborted!
can't modify frozen Hash
/app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/attributes.rb:190:in `[]='
/app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/attributes.rb:190:in `block in write_attribute'
/app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/threaded/lifecycle.rb:26:in `_assigning'
/app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/attributes.rb:180:in `write_attribute'
/app/vendor/bundle/ruby/1.9.1/gems/mongoid-3.1.4/lib/mongoid/fields.rb:437:in `block (2 levels) in create_field_setter'
/app/vendor/bundle/ruby/1.9.1/gems/delayed_job-3.0.5/lib/delayed/worker.rb:250:in `handle_failed_job'
/app/vendor/bundle/ruby/1.9.1/gems/delayed_job-3.0.5/lib/delayed/worker.rb:212:in `block in run'
```
- in worker.rb:212 (maybe in Job.destroy?) An Exception is rescued
- in worker.rb:250 when it executes handle_failed_job, the rake task crashes when it sets the field last_error

In local I don't have this problem.

For heroku I am using mongohq with dbversion 2.2.6 (I get the same problem also with version 2.4.6).

My delayed_job versions are:

delayed_job (3.0.5)
delayed_job_mongoid (2.0.0)

Any clue?

Thanks

**Comment by dblock** [comment]
I believe this is no longer a problem, or at least not with newer versions of Mongoid. Closing.
