### ISSUE TITLE
.delay doesn't work

### ISSUE THREAD

**Issue by danieljacobarcher** [collectiveidea/delayed_job_mongoid#48]
Having a problem using .delay on my mailers... I'm using dmitrydims fork for Rails 4 and Mongoid 4. Anyone else having the same problem?

**Comment by rdetert** [comment]
What kind of problem? I'm assuming you already know that you can't call `deliver` on the mailer when using `delay`.

**Comment by betamatt** [comment]
Please see https://github.com/collectiveidea/delayed_job#rails-3-mailers
