### ISSUE TITLE
Disable logging of job polling queries

### ISSUE THREAD

**Issue by doughsay** [collectiveidea/delayed_job_mongoid#54]
Is there a way to disable the MOPED logs from being added to the development.log or production.log file every time delayed job polls?  It adds a lot of noise to the log files and makes using `tail -f` on them really annoying, as every 5 seconds you get a MOPED query checking for new jobs...

**Comment by dblock** [comment]
This is old. Doing some bookkeeping. Have you figured this out @doughsay?

**Comment by doughsay** [comment]
No, we just sorta deal with it. Feel free to close.

**Comment by dblock** [comment]
I am going to label this a feature request and edit it a bit, I think it's a good idea.
