### ISSUE TITLE
Release a mongoid5-compatible version please

### ISSUE THREAD

**Issue by dblock** [collectiveidea/delayed_job_mongoid#59]

**Comment by sferik** [comment]
Coming right up! I just need to release an update to `delayed_job`, first.

**Comment by sferik** [comment]
@dblock There appear to be some test failures with version 4.1 of `delayed_job`, which I just released. Would you mind looking into those? I’d like to understand why their failing before I release.

**Comment by dblock** [comment]
Will do, stay tuned.

**Comment by aaani** [comment]
What's the status of this issue? We're using mongoid 5 and would like to use delayed_job with it.

**Comment by dblock** [comment]
2.2.0 has been released in September, this should have been closed.
