### ISSUE TITLE
Not working with Rails 5

### ISSUE THREAD

**Issue by OpticNectar** [collectiveidea/delayed_job_mongoid#68]
When I run the `rails jobs:work` command I get the error:
`Error while reserving job: undefined method 'find_and_modify'`

Is this gem not ready for Rails 5 or is there some other issue?

**Comment by heyrhett** [comment]
I get the same problem

**Comment by dblock** [comment]
https://github.com/collectiveidea/delayed_job_mongoid/pull/71 is green and will do the job.

**Comment by dblock** [comment]
Closing via https://github.com/collectiveidea/delayed_job_mongoid/pull/71.
