### ISSUE TITLE
Move to the mongoid organization?

### ISSUE THREAD

**Issue by dblock** [collectiveidea/delayed_job_mongoid#70]
Looks like things are a bit slow here. We'll gladly take this gem in the mongoid organization, https://github.com/mongoid. At the very least I'd love to help out with merging PRs, closing issues and making a release (dblock at dblock dot org on rubygems).

**Comment by sferik** [comment]
Sounds good to me. I’m not using DelayJob or Mongoid on any of my current projects, so I’m definitely not the best person to be maintaining this gem.

@dblock If you want to be added as a maintainer or transfer the repo to the @mongoid org, I think someone from @collectiveidea needs to help with that.

**Comment by dblock** [comment]
Thanks @sferik. If you have any time, would appreciate a review/merge of some of the open PRs.  

Maybe @albus522 or someone else can address ^? Thx.

**Comment by dblock** [comment]
@sferik gave me r/w access here and added me to rubygems, so I'll cleanup things and make a release and will try to help moving forward, leaving this open re: org

**Comment by dblock** [comment]
I got repo admin access, thanks @sferik. Closing this one. Will work on adding maintainers.
