### ISSUE TITLE
Incremental memory consumption

### ISSUE THREAD

**Issue by rjurado01** [collectiveidea/delayed_job_mongoid#76]
__System:__

* delayed_job (4.1.5)
* delayed_job_mongoid (2.3.0)
* mongoid (6.3.0)

__Problem__

After some time delayed_job process is taking all memory in development environment.

It seems that problem ocurrs only when we set `preload_models: true` into [mongoid configuration file](https://github.com/mongodb/mongoid/blob/master/lib/rails/generators/mongoid/config/templates/mongoid.yml#L121).

It could be related with this issues of delayed_job: 

* https://github.com/collectiveidea/delayed_job/issues/776
* https://github.com/collectiveidea/delayed_job/issues/823

**Comment by johnnyshields** [comment]
Try setting env var `MALLOC_ARENA_MAX=2` and see if that helps.

**Comment by johnnyshields** [comment]
I'm closing this. The main problem is that DelayedJob itself is not memory efficient, it needs to implement Copy-on-Write (CoW) forking. I started a PR here for that but it's still WIP https://github.com/collectiveidea/delayed_job/pull/1160
