### ISSUE TITLE
Delayed Job issue with Mongo transactions and job reservation

### ISSUE THREAD

**Issue by TheJohnzo** [collectiveidea/delayed_job_mongoid#83]
Hello, I'm running into some Mongo transaction issues. I have a cron task that queues up hundreds of delayed job records to be consumed by 2 workers. Each of those jobs may also trigger some other delayed jobs to be consumed by a different worker. (We are running 6 workers, total). The issue comes in below (see log) and crashes the worker process:

(Note: the workers that crash are processing the spin-off Delayed Jobs, not the main one processing the original 100s of records)

Log entry:
```
I, [2021-05-26T14:21:57.379990 #835]  INFO -- : 2021-05-26T14:21:57-0700: [Worker(delayed_job.0 host:jobsserver.staging.webserver.com pid:835)] 

Error while reserving job: Retryable write with txnNumber 11 is prohibited on session eae817b0-643f-4a5a-aacc-baae7ff9dbd9 - S8oMyTnRmLmiiib96wHuUHEe1v5gZMNm0MYQT5hrBs4= because a newer retryable write with txnNumber 406 has already started on this session. (225) (on web-staging-shard-00-00.stlfg.mongodb.net:27017, modern retry, attempt 1)
```
Could these be a bug?

Other system details:
```
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

    rails (5.2.5)
    mongoid (7.0.5)
      activemodel (>= 5.1, < 6.1)
      mongo (>= 2.5.1, < 3.0.0)
    delayed_job (4.1.9)
      activesupport (>= 3.0, < 6.2)
    delayed_job_mongoid (2.3.1)
      delayed_job (>= 3.0, < 5)
      mongoid (>= 3.0, < 8)
      mongoid-compatibility (>= 0.4.0)
```
I've also tried this on everything from `Mongoid 7.0.5` to `7.3.0` and on the Mongo gem up to `2.15.0.alpha`.

**Comment by johnnyshields** [comment]
AFAIK this gem doesn't use transactions. Can you provide a stack trace?

**Comment by johnnyshields** [comment]
Check your read/write concern. If you are using `w: majority`, that could be the issue. `w: 1` is recommended.

I'm going to close this. If you can setup an RSpec test (maybe use multi-threading) that can reproduce the issue, we can investigate. I'm using 100s of workers + jobs that spawn other jobs in prod with no such issue, so something must be going on funky in your database.
