### ISSUE TITLE
Postgres Deadlock

### ISSUE THREAD

**Issue by pebneter** [collectiveidea/delayed_job_mongoid#91]
Hello,

I have been using delayed_job for many years in my app and I couldn't be happier with the robustness I have seen.
Since a few days though I'm seeing Postgres deadlock error from time to time.
I have multiple processes working on the delayed jobs, but I don't think that should be a problem.

` Error while reserving job: PG::TRDeadlockDetected: ERROR: deadlock detected`
and 
```
STATEMENT: UPDATE "delayed_jobs" SET locked_at = '2023-01-24 23:17:34.600181', locked_by = 'host:bfa497____c5 pid:27' WHERE id IN (SELECT "delayed_jobs"."id" FROM "delayed_jobs" WHERE (((run_at <= '2023-01-24 23:17:34.599794' AND (locked_at IS NULL OR locked_at < '2023-01-24 23:17:04.599811')) OR locked_by = 'host:bfa497______9c5 pid:27') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
```
I'm a bit lost where to start debugging this. I have already done a Postgres vacuum since I read in a forum that it might help, but it didn't.

Any help is highly appreciated!

**Comment by TafadzwaD** [comment]
> Hello,
> 
> I have been using delayed_job for many years in my app and I couldn't be happier with the robustness I have seen. Since a few days though I'm seeing Postgres deadlock error from time to time. I have multiple processes working on the delayed jobs, but I don't think that should be a problem.
> 
> ` Error while reserving job: PG::TRDeadlockDetected: ERROR: deadlock detected` and
> 
> ```
> STATEMENT: UPDATE "delayed_jobs" SET locked_at = '2023-01-24 23:17:34.600181', locked_by = 'host:bfa497____c5 pid:27' WHERE id IN (SELECT "delayed_jobs"."id" FROM "delayed_jobs" WHERE (((run_at <= '2023-01-24 23:17:34.599794' AND (locked_at IS NULL OR locked_at < '2023-01-24 23:17:04.599811')) OR locked_by = 'host:bfa497______9c5 pid:27') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
> ```
> 
> I'm a bit lost where to start debugging this. I have already done a Postgres vacuum since I read in a forum that it might help, but it didn't.
> 
> Any help is highly appreciated!

@pebneter Any joy on this one? I am experiencing the same issue

**Comment by johnnyshields** [comment]
How would this be related to Delayed Job Mongoid??

**Comment by dblock** [comment]
It's not, @pebneter please open the issue in another repo.

**Comment by pebneter** [comment]
Hello there,
yes indeed, I opened the report in the wrong repo. Sorry!
The error has disappeared in the meantime, with no idea what made it so.
